### ISSUE TITLE
Null pointer on use-remote

### ISSUE THREAD

**Issue by sunng87** [sunng87/slacker#63]
2017-08-14 23:14:13,272 ERROR slacker.client.common: Unexpected error in event loop
java.lang.NullPointerException
        at slacker.serialization$eval2567$fn__2568.invoke(serialization.clj:48)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at slacker.client.common$parse_inspect_response.invokeStatic(common.clj:42)
        at slacker.client.common$parse_inspect_response.invoke(common.clj:40)
        at slacker.client.common$handle_response.invokeStatic(common.clj:47)
        at slacker.client.common$handle_response.invoke(common.clj:44)
        at slacker.client.common$create_link_handler$fn__3008.invoke(common.clj:345)
        at slacker.client.common$create_link_handler$fn__3042.invoke(common.clj:336)
        at slacker.client.common.proxy$io.netty.channel.SimpleChannelInboundHandler$ff19274a.channelRead0(Unknown Source)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at slacker.client.common.proxy$io.netty.channel.SimpleChannelInboundHandler$ff19274a.channelRead(Unknown Source)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.

**Comment by sunng87** [comment]
Fixed in 891f59a
